name: ${project.name}
version: ${project.version}
description: ${project.description}

authors: [NectarHoney]
main: me.nectarhoney.template.Template
website: https://github.com/JustDJplease/
softdepend: []

api-version: 1.13