name: ${project.name}
version: ${project.version}
description: ${project.description}

authors: [NectarHoney, Baksovic]
main: me.nectarhoney.itemizer.Itemizer
website: https://github.com/JustDJplease/
softdepend: []

api-version: 1.13

commands:
  itemizer:
    aliases: [modifyitem, it, ii]
    description: ${project.description}